# Generated by Django 4.1.4 on 2023-03-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tweet',
        ),
    ]
