# Generated by Django 4.1.4 on 2023-03-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
    ]
