# Generated by Django 4.1.4 on 2023-03-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_begeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like',
            field=models.IntegerField(null=True, verbose_name='likes'),
        ),
    ]
