# Generated by Django 4.1.4 on 2023-03-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_tweet_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
    ]
