# Generated by Django 4.1.4 on 2023-03-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_alter_begeni_tveet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Begeni',
        ),
    ]
