# Generated by Django 4.1.4 on 2023-03-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_tweet_tweet_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_likes',
        ),
    ]
