# Generated by Django 4.1.4 on 2023-03-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_remove_tweet_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_likes',
            field=models.IntegerField(default=0, verbose_name='tweet_Likes'),
        ),
    ]
