# Generated by Django 4.1.4 on 2023-03-11 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0019_remove_tweet_tweet_likes_begeni_value_tweet_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='folowed',
            field=models.ManyToManyField(blank=True, default=None, related_name='folowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Folow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Flow', 'Flow'), ('Unfolow', 'Unfolow')], default='Folow', max_length=10)),
                ('twiit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.tweet', verbose_name='Tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
